### PR TITLE
rolling_hash: Implement rolling_hash2 for aarch64

### PR DESCRIPTION
**Pull request by yuhaoth**
Change-Id: I1b57b18a7e5d0f7365c0550086e75802f065238f
Signed-off-by: Jerry Yu <jerry.h.yu@arm.com>

### CODE REVIEW

**Comment by yuhaoth** [comment]
@gbtucker please review

**Comment by yuhaoth** [comment]
@gbtucker  , just update it , please review

**Comment by gbtucker** [comment]
Is it possible that you pushed this update to the wrong PR? The new update to this has title "sm3_mb:Add sm3_mb_test"

**Comment by yuhaoth** [comment]
oops， I do wrong operation

**Comment by gbtucker** [comment]
@yuhaoth, does this pass the CI tests?  I get a lot of 'dangerous relocation' errors when trying to cross-compile.  Also some commented code in the _dispatcher.c.

**Comment by yuhaoth** [comment]
> 
> 
> @yuhaoth, does this pass the CI tests? I get a lot of 'dangerous relocation' errors when trying to cross-compile. Also some commented code in the _dispatcher.c.

Yes，It pass CI tests . 
Could you share build log and compiler information?

**Comment by gbtucker** [comment]
As I looked into the error I see that the issue was on my end.  Sorry, I'll schedule for integration.

**Pull request merged**
