### PR TITLE
fix redefined warning on aarch64 when using autoconf 2.71

### PR DESCRIPTION
**Pull request by chenxuqiang**
Fix compilation warning: [issues #124](https://github.com/intel/isa-l_crypto/issues/124)

### CODE REVIEW

**Comment by pablodelara** [comment]
Thanks @chenxuqiang. Anyone from ARM/using ARM that can review this?

**Comment by chenxuqiang** [comment]
I verified the above modifications using autoconf 2.69 and autoconf 2.70, respectively, and passed on both `AARCH64` and `X86`.

**Comment by docularxu** [comment]
Thanks @chenxuqiang 
With that, I'm +1 on this patch.

**Comment by pablodelara** [comment]
Merged in [f2e0339](https://github.com/intel/isa-l_crypto/commit/f2e0339bbdcd7d64c7a0015722d456c0405b46f9), thanks!

**Pull request closed without merging**
