### PR TITLE
Add stream api std tests

### PR DESCRIPTION
**Pull request by yuhaoth**
That‘s a share of my debug code.

To debug stream api with random test is difficult for developer. I set some cases to improve std test coverage. 
That might reduce developer's loading.

Those test case will trigger partial block routines.

### CODE REVIEW

**Comment by yuhaoth** [comment]
@gbtucker please review .

**Comment by gbtucker** [comment]
Thanks for adding to the test cases.  This is great but it currently breaks when the compile option NT_LDST is set.  If you can see the test `aes/gcm_std_vectors_random_test.c` has options for limiting alignment when this is turned on for random tests.  I'm not sure how to limit for the std tests when the updates are so small.

**Comment by yuhaoth** [comment]
oops, I will check that.

**Comment by yuhaoth** [comment]
There are aes_gcm*_nt functions ,  Is NT_LDST still needed? If defined , the behavior is same with _nt functions.

And in  aes/gcm_std_vectors_random_test.c , the update length always be multiple of 64 . Is it also a restriction ?

**Comment by gbtucker** [comment]
That is a correct restriction.  Perhaps just add for now.
```
#if !defined(NT_LD) && !defined(NT_ST) && !defined(NT_LDST)
        errors += test_gcm_std_strm_vectors();
#endif
```

**Comment by yuhaoth** [comment]
Got it , the update is in internal review

**Comment by yuhaoth** [comment]
@gbtucker , just update it . Please review

**Comment by gbtucker** [comment]
Looks good, I'll schedule for integration.

**Comment by gbtucker** [comment]
Integrated

**Pull request closed without merging**
