### PR TITLE
Fix endian helper for distcheck and internal only

### LINKED ISSUE #59: Dependence on endian_helper.h which isn't installed
When building my library against latest master, we get the following:

In file included from install/prereq/dev/isal_crypto/include/isa-l_crypto/md5_mb.h:108,
                 from install/prereq/dev/isal_crypto/include/isa-l_crypto.h:20,
                 from src/common/multihash_isal.c:32:
install/prereq/dev/isal_crypto/include/isa-l_crypto/multi_buffer.h:43:10: fatal error: endian_helper.h: No such file or directory
   43 | #include "endian_helper.h"

It seems this file needs to be available or has leaked into external headers.

### PR DESCRIPTION
**Pull request by gbtucker**
Previously included file endian_helper.h was not included in the
distribution list and was included by external headers. This changes
the includes to be local only and puts file in non-external dist list.
Also fixes other missing extra-dist.

Fixes #59

Change-Id: I643da8c26b6136a9f1bba5493936dd1184c217d5
Signed-off-by: Greg Tucker <greg.b.tucker@intel.com>

### CODE REVIEW

**Comment by gbtucker** [comment]
@uweigand, @jolivier23 please take a look.

**Comment by uweigand** [comment]
Ah, sorry.  I didn't realize there was a distinction between external and internal headers.

In any case, this patch looks good to me as far as the platform-independent files are concerned.   However, it looks like a couple of AArch64 files were missed:
sha1_mb/aarch64/sha1_ctx_ce.c
sha256_mb/aarch64/sha256_ctx_ce.c
sha512_mb/aarch64/sha512_ctx_ce.c
sm3_mb/aarch64/sm3_mb_ctx_asimd_aarch64.c
sm3_mb/aarch64/sm3_mb_ctx_sm_aarch64.c

**Comment by gbtucker** [comment]
@uweigand, it looks like those aarch64 files take care of endianness in their own way.  I'm not sure if big endian is supported there.

**Comment by uweigand** [comment]
@gbtucker my point was that my patch added calls to the new to_be64() routines defined in endian_helper.h to these files, so without the include they won't compile any more.

If those files don't need to support big-endian hosts, then as an alternative to adding the include the changes from my patch to those files could be reverted again -- but either way some change is necessary for the files to build again after the removal of the #include "endian_helper.h" from multi_buffer.h

**Comment by gbtucker** [comment]
Ah, thanks @uweigand.  I'll fix those also.

**Comment by jolivier23** [comment]
DAOS builds again with this patch.  Thanks

**Pull request merged**
